/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OsintRouteImport } from './routes/osint'
import { Route as PlanilhaRouteImport } from './routes/planilha'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SynxSearchRouteImport } from './routes/synx-search'
import { Route as ApiProxyRouteImport } from './routes/api.proxy'
import { Route as ModuleIdRouteImport } from './routes/module.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OsintRoute = OsintRouteImport.update({
  id: '/osint',
  path: '/osint',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanilhaRoute = PlanilhaRouteImport.update({
  id: '/planilha',
  path: '/planilha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SynxSearchRoute = SynxSearchRouteImport.update({
  id: '/synx-search',
  path: '/synx-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleIdRoute = ModuleIdRouteImport.update({
  id: '/module/$id',
  path: '/module/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/osint': typeof OsintRoute
  '/planilha': typeof PlanilhaRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/synx-search': typeof SynxSearchRoute
  '/api/proxy': typeof ApiProxyRoute
  '/module/$id': typeof ModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/osint': typeof OsintRoute
  '/planilha': typeof PlanilhaRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/synx-search': typeof SynxSearchRoute
  '/api/proxy': typeof ApiProxyRoute
  '/module/$id': typeof ModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/osint': typeof OsintRoute
  '/planilha': typeof PlanilhaRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/synx-search': typeof SynxSearchRoute
  '/api/proxy': typeof ApiProxyRoute
  '/module/$id': typeof ModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/osint'
    | '/planilha'
    | '/profile'
    | '/settings'
    | '/synx-search'
    | '/api/proxy'
    | '/module/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/osint'
    | '/planilha'
    | '/profile'
    | '/settings'
    | '/synx-search'
    | '/api/proxy'
    | '/module/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/osint'
    | '/planilha'
    | '/profile'
    | '/settings'
    | '/synx-search'
    | '/api/proxy'
    | '/module/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  OsintRoute: typeof OsintRoute
  PlanilhaRoute: typeof PlanilhaRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SynxSearchRoute: typeof SynxSearchRoute
  ApiProxyRoute: typeof ApiProxyRoute
  ModuleIdRoute: typeof ModuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osint': {
      id: '/osint'
      path: '/osint'
      fullPath: '/osint'
      preLoaderRoute: typeof OsintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planilha': {
      id: '/planilha'
      path: '/planilha'
      fullPath: '/planilha'
      preLoaderRoute: typeof PlanilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synx-search': {
      id: '/synx-search'
      path: '/synx-search'
      fullPath: '/synx-search'
      preLoaderRoute: typeof SynxSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/$id': {
      id: '/module/$id'
      path: '/module/$id'
      fullPath: '/module/$id'
      preLoaderRoute: typeof ModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  OsintRoute: OsintRoute,
  PlanilhaRoute: PlanilhaRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SynxSearchRoute: SynxSearchRoute,
  ApiProxyRoute: ApiProxyRoute,
  ModuleIdRoute: ModuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
